# Generated by Django 4.2.6 on 2023-10-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_coursemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionYearModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionStart', models.CharField(max_length=100)),
                ('sessionEnd', models.CharField(max_length=100)),
            ],
        ),
    ]
